version: '3.6'
services:
    postgres:
      image: postgres:13-alpine
      restart: "no"
      ports:
        - "5432:5432"
      volumes:
        - assez-dechets-postgres:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: assez-dechets-project
        POSTGRES_USER: assez-dechets
        POSTGRES_PASSWORD: superSecretPassword
    # postgres-test:
    #   image: postgres:13-alpine
    #   restart: "no"
    #   ports:
    #     - "5433:5433"
    #   volumes:
    #     - assez-dechets-postgres-test:/var/lib/postgresql/data
    #   environment:
    #     POSTGRES_DB: assez-dechets-project-test
    #     POSTGRES_USER: assez-dechets-test
    #     POSTGRES_PASSWORD: testPassword
volumes:
  assez-dechets-postgres:
  # assez-dechets-postgres-test: