###
GET http://localhost:3000/api/events

###
GET http://localhost:3000/api/events/2

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
    "title": "Super collecte",
    "place": "Trifouilly-les-Canards",
    "startDate": "2018-01-01",
    "endDate": "2018-01-02",
    "description": "C'est la fête des canards",
    "status": "UPCOMING",
    "weight": 10,
    "creatorId": 1

}

###

PUT http://localhost:3000/api/events/1
Content-Type: application/json

{
    "place": "Turlututu"
}

###

DELETE http://localhost:3000/api/events/8

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "gfgqaavgfgfh@test.com",
  "password": "turlututu"
}