###
GET http://localhost:3000/api/events

###
GET http://localhost:3000/api/events/2

###

POST http://localhost:3000/api/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjY2NTk5NDkxLCJleHAiOjE2NjY2MDMwOTF9.wJSKIDk9ROrsH29gU5mbeZ_rkOJdnf8YQ2f4YqI7QYw

{
    "title": "Super collecte",
    "place": "Trifouilly-les-Canards",
    "startDate": "2022-10-12",
    "endDate": "2022-11-02",
    "description": "C'est la fête des canards",
    "status": "UPCOMING",
    "weight": 10,
    "creatorId": 2

}

###

PUT http://localhost:3000/api/events/1
Content-Type: application/json

{
    "place": "Turlututu"
}

###

DELETE http://localhost:3000/api/events/8

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "firstName": "test",
  "lastName": "test",
  "email": "fddgfg@test.com",
  "password": "P@ff!ssw0rd"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "fddgfg@test.com",
  "password": "P@ff!ssw0rd"
}

###
POST http://localhost:3000/api/:eventId/:userId